root = "."
tmp_dir = "air_tmp"

[build]
cmd = "go build -o ./air_tmp/labe ."
entrypoint = ["./air_tmp/labe"]
include_ext = ["go"]
exclude_dir = ["air_tmp", "assets"]
send_interrupt = true
kill_delay = "500ms"

[misc]
clean_on_exit = true
startup_banner = '''
 _      __    ___   ____        __    _   ___
| |    / /\  | |_) | |_        / /\  | | | |_)
|_|__ /_/--\ |_|_) |_|__  on  /_/--\ |_| |_| \_
'''
